### ISSUE TITLE
Instructions on how to build packages yourself

### ISSUE THREAD

**Issue by FooBarWidget** [fullstaq-labs/fullstaq-ruby-server-edition#1]
In order to promote users to be independent, i.e. to allow them to operate even when we are slow or defunct, users should be able to build packages themselves. Avoiding vendor lock-in, so to say. We should have better documentation on how users can build packages themselves.

This does *not* include instructions on how to build for a different Ruby or Jemalloc version. That would be part of the [developer/contribution documentation](https://github.com/fullstaq-labs/fullstaq-ruby-project/projects/3).

**Comment by ndbroadbent** [comment]
Hello, I would also like to add my +1 to this issue, related to adding Debian 10 support (#16)

I've forked the `fullstaq-ruby-server-edition` repo and am trying to add support for this myself so I can submit a PR, but I'm not sure where to start or what scripts I should run. But if I can figure it out, then I will send a PR. Thanks!

**Comment by FooBarWidget** [comment]
Implemented through the development handbook (see `dev-handbook/`)
