### ISSUE TITLE
Debian 10 support

### ISSUE THREAD

**Issue by FooBarWidget** [fullstaq-labs/fullstaq-ruby-server-edition#16]
We should build packages for Debian 10.

**Comment by ndbroadbent** [comment]
Hello, this would be great! I would love to upgrade to Debian 10 and use the fullstaq Ruby package so that I don't need to compile it myself. 

I tried the `debian-9` source but I get the following error:

```
The following packages have unmet dependencies:
 fullstaq-ruby-2.5.7-jemalloc : Depends: libgdbm3 (>= 1.8.3) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Thanks for supporting these packages!
