### ISSUE TITLE
Ruby 2.6.4

### ISSUE THREAD

**Issue by mmainz** [fullstaq-labs/fullstaq-ruby-server-edition#19]
Ruby 2.6.4 has been out for about two weeks now. But I don't see a package for it anywhere. Using the 2.6 package also still yields me version 2.6.3. Are you going to release an updated version soon?

**Comment by FooBarWidget** [comment]
Yes.

**Comment by FooBarWidget** [comment]
Depends on #20

**Comment by FooBarWidget** [comment]
Packages built and uploaded. Still not entirely happy about the automation, but let's take care of that later.
