### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by FooBarWidget** [fullstaq-labs/fullstaq-ruby-server-edition#2]
We should build packages for Ubuntu 20.04.

**Comment by FooBarWidget** [comment]
Now that Ubuntu 20.04 is out, we may as well skip 19.04.

**Comment by njosefbeck** [comment]
Would love having 20.04 support!

**Comment by manuelmeurer** [comment]
Is there a timeline for this?

**Comment by manuelmeurer** [comment]
@FooBarWidget Is there anything I can do to help with this?

**Comment by FooBarWidget** [comment]
I would welcome a pull request.

Otherwise, it depends on my free time. Which, for now, is ad-hoc and unpredictable.

**Comment by FooBarWidget** [comment]
Looks like I have some time this afternoon. I'll publish some work in progress and see how far I get.

**Comment by manuelmeurer** [comment]
Awesome, let me know if I can help with anything! 🙌

**Comment by FooBarWidget** [comment]
Support has been added. As soon as the CI/CD system finishes, the packages will be released.

**Comment by FooBarWidget** [comment]
There is a problem with the Ubuntu 20.02 package. Looks like Bintray's API doesn't like it if I try to add an existing package (fullstaq-ruby-common) to a new distribution. I'll need to find a workaround for this.

**Comment by FooBarWidget** [comment]
Workaround found, applied and deployed. Should work now.
