### ISSUE TITLE
rbenv can't find installed Ruby version

### ISSUE THREAD

**Issue by vitobotta** [fullstaq-labs/fullstaq-ruby-server-edition#21]
Hi! I am trying to get fullstaq-ruby to work with a Docker container. Both the fullstaq-ruby-2.6-jemalloc and rbenv packages are installed, and I can run `/usr/lib/fullstaq-ruby/versions/2.6-jemalloc/bin/ruby -v`, but if I run `rbenv versions` it only finds the system Ruby. How do I tell rbenv where to look for the correct Ruby versions? Thanks!

**Comment by vitobotta** [comment]
I had to run `ln -s /usr/lib/fullstaq-ruby/versions $HOME/.rbenv/` before running `rbenv init`. Only that way rbenv sees the versions installed.

**Comment by FooBarWidget** [comment]
Did you have the `rbenv` package installed, or the `fullstaq-rbenv`? We supply a patched rbenv that looks in /usr/lib/fullstaq-ruby/versions.

**Comment by vitobotta** [comment]
Hi, I currently install the rbenv package. Should it be fullstaq-rbenv instead? Thanks

**Comment by FooBarWidget** [comment]
Yes it must be fullstaq-rbenv specifically.

**Comment by vitobotta** [comment]
Hi @FooBarWidget , with that package I no longer need that symlink. Thanks!
