### ISSUE TITLE
Document usage with sudo

### ISSUE THREAD

**Issue by zhum** [fullstaq-labs/fullstaq-ruby-server-edition#22]
After installing fullstaq-rbenv and fullstaq-ruby-2.6.4-jemalloc from repository and all preparations from wiki (delete ~/.rbenv/bin from PATH and init with fullstaq rbenv)  I still cannot use fullstaq ruby as regular user:
```
$ rbenv --version
rbenv 1.1.2
$ rbenv exec ruby -v
ruby 2.6.4p104 (2019-08-28 revision 67798)+jemalloc [x86_64-linux]
$ rbenv exec gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/lib/fullstaq-ruby/versions/2.6.4-jemalloc/lib/ruby/gems/2.6.0 directory.
```

**Comment by FooBarWidget** [comment]
What you're showing is how it is supposed to work. Fullstaq Ruby is installed to a system location (/usr/lib/fullstaq-ruby), which a normal user has no write permissions to. You should use 'sudo'.

But I see that this point could be confusing (especially because 'rbenv' changes environment variables while 'sudo' nukes environment variables). There should be documentation about the need to use 'sudo', and how to use it.

**Comment by westonganger** [comment]
+1 please document this. 

This results in a new workflow change for some. Before this change I did not have to prefix all my commands with `rbenv exec` but now with the `sudo` requirement I now must use `sudo rbenv exec gem install bundler`

**Comment by westonganger** [comment]
You can get around this by changing the group of the fullstaq-ruby folder with the following permissions changes:

- groupadd your-group (optional if group already exists)
- usermod -a -G your-group $USER (optional if users already in group)
- chgrp your-group /usr/lib/fullstaq-ruby
- chmod g+srwx /usr/lib/fullstaq-ruby

**Comment by evenreven** [comment]
I'm trying @westonganger's method on CentOS 8, but I'm getting this error:

```
Traceback (most recent call last):
	2: from /usr/lib/rbenv/versions/2.6.6-jemalloc/bin/gem:9:in `<main>'
	1: from /usr/lib/fullstaq-ruby/versions/2.6.6-jemalloc/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/fullstaq-ruby/versions/2.6.6-jemalloc/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': Insecure operation - gem_original_require (SecurityError)
```

Here's what I did:

```bash
su deploy-user # has sudo rights
sudo dnf install fullstaq-ruby-common fullstaq-ruby-2.6.6-jemalloc
sudo groupadd rbenv
sudo usermod -aG rbenv deploy-user
sudo chgrp -R rbenv /usr/lib/fullstaq-ruby
sudo chmod -R g+swrx /usr/lib/fullstaq-ruby
rbenv rehash # probably unnecessary
rbenv global 2.6.6-jemalloc
rbenv exec gem install bundler
```

I also tried to set it on only the /usr/lib/rbenv directory (and I tried on both), but the former gives a regular permissions error, and the second gives the same `require': Insecure operation - gem_original_require (SecurityError)`

Is this meant to work now, or did I do something wrong somewhere? I'd very much like to avoid using sudo when I run gem and bundle, but I can live with it if this can't be done any other way.

**Comment by FooBarWidget** [comment]
I added documentation now.
