### ISSUE TITLE
The minor version package doesn't track the tiny version package

### ISSUE THREAD

**Issue by sudo-nice** [fullstaq-labs/fullstaq-ruby-server-edition#23]
Hello, I have `fullstaq-ruby-2.6` installed and expect it to contain the last tiny version `ruby2.6.4`, but it still contains `ruby2.6.3`.

The [documentation] says the minor release should be tracking the last tiny release, but that doesn't happen for me. I'm not sure, if that's a bug or it's just me doing something wrong.

```
rbenv -v                  # rbenv 1.1.2
rbenv versions            # * 2.6 (set by /home/user/.rbenv/version)
rbenv exec ruby --version # ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
ruby -v                   # ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

```
If it matters, I'm on Debian 10, but used the recommended method for installing fullstaq-ruby on Debian 9.

```
apt show fullstaq-ruby-2.6
  Package: fullstaq-ruby-2.6
  Version: 1-debian-9
  Priority: extra
  Section: default
  Maintainer: Fullstaq <info@fullstaq.com>
  Installed-Size: 19.8 MB
  Provides: fullstaq-ruby
  Depends: libc6 (>= 2.17), libffi6 (>= 3.0.4), libgdbm3 (>= 1.8.3), libncurses5 (>= 6), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo5 (>= 6), libyaml-0-2, zlib1g (>= 1:1.2.2)
  Recommends: fullstaq-ruby-common
  Homepage: https://github.com/fullstaq-labs/fullstaq-ruby-server-edition
  License: BSD 2-clause
  Vendor: Fullstaq
  Download-Size: 6,827 kB
  APT-Manual-Installed: yes
  APT-Sources: https://apt.fullstaqruby.org debian-9/main amd64 Packages
  Description: Fullstaq Ruby 2.6
   Package version with variant suffix: 2.6
   Package version without variant suffix: 2.6
   Variant: normal
   Distribution: debian-9
```

[documentation]: https://github.com/fullstaq-labs/fullstaq-ruby-server-edition#minor_version_packages

**Comment by FooBarWidget** [comment]
Looks like I forgot to upload that particular package. Fixed now.

The current release process is manual and is prone to human errors like this. This is why [epic 3](https://github.com/fullstaq-labs/fullstaq-ruby-umbrella/projects) is so important: with the proper CI/CD infrastructure in place such mistakes won't happen anymore.
