### ISSUE TITLE
Allow for rbenv install for other Ruby versions

### ISSUE THREAD

**Issue by westonganger** [fullstaq-labs/fullstaq-ruby-server-edition#28]
Can we allow for `rbenv install` so that older Rubies and other versions of Ruby can be installed?

**Comment by FooBarWidget** [comment]
`rbenv install` still works, but it always installs to ~/.rbenv.

**Comment by westonganger** [comment]
I am not able to use the `install` command, see below

```
$ rbenv install
rbenv: no such command `install'
```

Also I was hoping that the rubies could be installed globally, the behaving the same as the fullstaq rubies.

**Comment by FooBarWidget** [comment]
You need to install the ruby-build rbenv plugin first.

>

**Comment by westonganger** [comment]
Ok, in my server environment I am trying to avoid `~/.rbenv` since it should be possible to do it all at the system level.
