### ISSUE TITLE
RHEL/CentOS 8 support

### ISSUE THREAD

**Issue by FooBarWidget** [fullstaq-labs/fullstaq-ruby-server-edition#3]
We should build packages for RHEL/CentOS 8. We either need to figure out how to use the RHEL Docker images (it is said that they provide free developer licenses), or we need to wait for CentOS 8 to be released.

**Comment by kule** [comment]
Did you mean Redhat/Centos 8?

**Comment by FooBarWidget** [comment]
Yes that was a typo.

**Comment by wollistik** [comment]
Any news on this. I am very interested in this package and would like to test it in our production environment.

**Comment by FooBarWidget** [comment]
I haven't started working on this, although a pull request would also be appreciated. Now that our CI/CD system is done, once the code changes are there, new packages can be released pretty quickly.

**Comment by wollistik** [comment]
I made a pull request for this. See #48
