### ISSUE TITLE
Debian 10 not fully released yet?

### ISSUE THREAD

**Issue by xtr3me** [fullstaq-labs/fullstaq-ruby-server-edition#35]
At this moment the Readme states to use the following line in my apt sources list:
```
# Debian 10
deb https://apt.fullstaqruby.org debian-10 main
```

But when trying to install it gives an error:
```
E: The repository 'https://apt.fullstaqruby.org debian-10 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Probably because the following server doesn't have the debian-10 directory:
https://dl.bintray.com/fullstaq/fullstaq-ruby-apt/dists/
```
debian-9/
ubuntu-18.04/
```

**Comment by FooBarWidget** [comment]
Yes. Support for building Debian 10 packages has been merged the other day, but packages haven't actually been built and published yet.

**Comment by stevehill1981** [comment]
Pretty please could we have Debian 10 packages soon? :)

**Comment by renchap** [comment]
Or more specifically, any way we can help to get them published? :)

**Comment by FooBarWidget** [comment]
Yes I'll make releasing Debian 10 packages a priority.

As for publishing them faster in the future: a Continuous Deployment system is being developed, which will help a lot towards that goal.

**Comment by stevehill1981** [comment]
Thank you! 😁
