### ISSUE TITLE
Ruby 2.7.0

### ISSUE THREAD

**Issue by Envek** [fullstaq-labs/fullstaq-ruby-server-edition#36]
Ruby 2.7 was released on Christmas (as planned) and it would be awesome to have packages for it here with jemalloc and other patches as well.

https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

Thank you for your work on fullstaq-ruby!

**Comment by FooBarWidget** [comment]
Thanks for the heads-up Envek. I'll make this a priority.

**Comment by FooBarWidget** [comment]
Implemented in 0641e5622 and released. Enjoy!

**Comment by Envek** [comment]
Thank you very much! :pray:
