### ISSUE TITLE
Support for Ruby 2.7.1, 2.6.6, 2.5.8

### ISSUE THREAD

**Issue by rasbary** [fullstaq-labs/fullstaq-ruby-server-edition#39]
These minor updates were released today and contain security fixes:
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-5-8-released/

**Comment by FooBarWidget** [comment]
CI/CD support has just been finished this week! This is a great chance to test whether it works properly.

**Comment by FooBarWidget** [comment]
The versions have now been bumped. As long as the CI/CD system finishes, these packages will be published.

**Comment by FooBarWidget** [comment]
It appears we have been rate limited by Bintray, probably because of the large amounts of activity to Bintray lately due to working on the CI/CD system. So I cannot publish anything yet. I'll contact Bintray to see how to resolve this.

**Comment by Envek** [comment]
Oh, this is so unfortunate! Can you please reopen this issue until you'll be able to publish packages? Thank you!

**Comment by FooBarWidget** [comment]
Packages published. Enjoy!
