### ISSUE TITLE
Error attempting to use fullstaq ruby on OpsWorks xenial ubuntu stack.

### ISSUE THREAD

**Issue by mileslane** [fullstaq-labs/fullstaq-ruby-server-edition#40]
Hit:9 https://download.newrelic.com/infrastructure_agent/linux/apt xenial InRelease
Ign:11 https://apt.fullstaqruby.org ubuntu-16.04 InRelease
Ign:12 https://apt.fullstaqruby.org ubuntu-16.04 Release
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Ign:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Err:13 https://apt.fullstaqruby.org ubuntu-16.04/main amd64 Packages
404  Not Found
Ign:14 https://apt.fullstaqruby.org ubuntu-16.04/main all Packages
Ign:15 https://apt.fullstaqruby.org ubuntu-16.04/main Translation-en
Reading package lists...
STDERR: W: The repository 'https://apt.fullstaqruby.org ubuntu-16.04 Release' does not have a Release file.
E: Failed to fetch https://apt.fullstaqruby.org/dists/ubuntu-16.04/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by FooBarWidget** [comment]
Sorry, we don't support Ubuntu 16.04. Ubuntu 18.04 is required.
