### ISSUE TITLE
Conflicts with file from package error on installation

### ISSUE THREAD

**Issue by daan-b** [fullstaq-labs/fullstaq-ruby-server-edition#44]
Installed Fullstaq on a CentOS 7 server. 

**Installed packages:**
fullstaq-rbenv.noarch 1.1.2-1 @fullstaq-ruby
fullstaq-ruby-2.6-jemalloc.x86_64 rev5-centos7 @fullstaq-ruby 
fullstaq-ruby-common.noarch 1.0-0 @fullstaq-ruby

Everything works fine. Now I want to install the 2.7 version also so I run:

`sudo yum install fullstaq-ruby-2.7-jemalloc.x86_64`

Got error:

`Transaction check error:
  file /usr/lib/.build-id/bb/b8242dc9965a6238d9c0f9360487395b95f53b from install of fullstaq-ruby-2.7-jemalloc-rev1-centos7.x86_64 conflicts with file from package fullstaq-ruby-2.6-jemalloc-rev5-centos7.x86_64
  file /usr/lib/.build-id/bb/b8242dc9965a6238d9c0f9360487395b95f53b.1 from install of fullstaq-ruby-2.7-jemalloc-rev1-centos7.x86_64 conflicts with file from package fullstaq-ruby-2.6-jemalloc-rev5-centos7.x86_64`

Any ideas?

The installation of the 'normal' variant (fullstaq-ruby-2.7.x86_64) works fine.

**Comment by FooBarWidget** [comment]
This bug has been confirmed. /usr/lib/.build-id/bb/b8242dc9965a6238d9c0f9360487395b95f53b is a symlink to jemalloc. The jemalloc library is built once per distribution, so it's binary identical in all Ruby packages for that distribution, which results in it having the same build ID in those Ruby packages. Unfortunately that results in filename clashes.

The easiest fix is to not package the build IDs.

**Comment by FooBarWidget** [comment]
The issue has been fixed now. When the Continuous Deployment system finishes, you'll receive package updates.
