### ISSUE TITLE
Bad URL for fullstaq-labs github organization

### ISSUE THREAD

**Issue by westonganger** [fullstaq-labs/fullstaq-ruby-server-edition#45]
On the github organization here: https://github.com/fullstaq-labs

The website is listed as: https://www.fullstaq.com

This links to some other companies website. I dont think that this is desired. 

Also the members of this group does not include @FooBarWidget which seems odd.

Is there something malicious going on here?

**Comment by FooBarWidget** [comment]
Thanks for the comment. This is in fact correct. Fullstaq Ruby is a collaboration between myself (Hongli Lai) and Fullstaq (whose website is fullstaq.com and Github org is fullstaq-labs). This affiliation is also documented in the readme and on fullstaqruby.org.
