### ISSUE TITLE
Release blocker: we're hitting CI size limits

### ISSUE THREAD

**Issue by FooBarWidget** [fullstaq-labs/fullstaq-ruby-server-edition#62]
Further Fullstaq Ruby releases are currently blocked because the CI is broken. It appears that we're running into some sort of Github Actions size limit for the workflow file.

Note: this is a limit on *workflow files*, not a limit on artifact sizes, number of jobs, or even CI run times.

I've [inquired](https://github.community/t/max-workflow-file-size/135445) about what exactly the size limit is, but there's no good answer so far. My best estimate is that it's either around 500 KB or around 800 KB (seems to vary over time).

The complexity of our build system doesn't allow shrinking the workflow file much further. I'm currently investigating alternatives to work around Github Actions size limits. Maybe we can split up the workflow file into multiple parts, but it's not yet clear how to achieve that.

**Comment by PaulusTM** [comment]
Would it work if we split the build per OS? This way we could also run build for specific builds if needed.

So a build for:
- Ubuntu
- CentOS
- Debian

**Comment by FooBarWidget** [comment]
Splitting is the easy part. Coordinating everything into a single, atomic whole is the hard part. We want to publish all packages as a single unit, so that we can't have releases that are half-published.

**Comment by renchap** [comment]
Would it be possible to do things in 2 parts?

First you build everything, with specific builds, and then another build does the publication, in one single step.

**Comment by FooBarWidget** [comment]
That's the goal. The question is how. I can trigger the publication workflow from the build workflow, but I also want the publication workflow to show up in the commit's list of checks. I'm experimenting with the Checks API to see whether I can make that work.

**Comment by FooBarWidget** [comment]
One more complication: I'm not actually able to trigger another workflow from a workflow.

Inside one workflow, when I call the workflow dispatch API, the API call succeeds, but it doesn't actually trigger the second workflow.

**Comment by thomaspeitz** [comment]
Would it be in your interest, to further move scripts out of the main yml into sub actions like this for example? (pseudo, not sure if it works like that)

![image](https://user-images.githubusercontent.com/8327755/95718815-a099af00-0c77-11eb-9fd4-3c99d67f1009.png)

Same goes for e.g. where several steps could get into an sub action as well:
![image](https://user-images.githubusercontent.com/8327755/95719049-f66e5700-0c77-11eb-9f2d-3d75534ebd26.png)

Could prepare a PR if there is interest.

**Comment by FooBarWidget** [comment]
Thanks for the suggestion @thomaspeitz. Unfortunately, I don't think splitting into sub-actions will work. That's because composite steps can only invoke `run` steps, not `uses` steps. So they're little more than glorified shell scripts. On the other hand, we *already* put most logic into shell script files, not in the workflow YAML file.

I think the most viable solution is to:

 1. Split the workflow file into multiple workflow files.
 2. Have the main workflow trigger other workflows, using the Github API.
 3. Have the main workflow keep track of the sub-workflows' status, by creating and updating checks using the Checks API.

I've run some experiments lately and this approach seems to work, even if it's sub-optimal.

**Comment by FooBarWidget** [comment]
Releasing a fix now. Hoping that it works when run on `main`.

**Comment by FooBarWidget** [comment]
Yeah, I knew it wasn't going to go that smoothly. Continuing the fix.

**Comment by FooBarWidget** [comment]
Looks like the CI/CD system is indeed fixed. But now we're running into issues in Bintray. Somehow they're not generating the APT index files properly, causing checksum mismatches. I'll email support. :(

We should move away from Bintray one day.

**Comment by FooBarWidget** [comment]
I've just fixed this myself by reuploading some files to force Bintray to regenerate the APT metadata.

I've also added docs for the new split-up CI/CD system: https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/blob/main/dev-handbook/ci-cd-split-multiple-workflows.md
