### ISSUE TITLE
Migrate away from Bintray

### ISSUE THREAD

**Issue by FooBarWidget** [fullstaq-labs/fullstaq-ruby-server-edition#70]
JFrog is sunsetting Bintray by May 2021. We must migrate away before that date.

One of the options is to build an APT server ourselves, perhaps using [Pulp](https://pulpproject.org/).

**Comment by manuelvanrijn** [comment]
Could this get more priority? At this point they are as they describe it:

> We will have some short service brown-outs to remind users about the services that are going away on May 1st. (Specific hours will be advertised in the Bintray status page.)

Meaning unable to use the apt source between April 12th 6AM to 2PM Pacific Daylight Time :/

**Comment by jordanfbrown** [comment]
Echoing @manuelvanrijn's sentiment as well. Started off our Monday morning with our builds failing because https://apt.fullstaqruby.org is returning a 502 error (due to maintenance on Bintray's side)

https://status.bintray.com/

![image](https://user-images.githubusercontent.com/467728/114408049-a90f6b80-9b6e-11eb-8085-da77f41b4be5.png)

**Comment by FooBarWidget** [comment]
I have scheduled the next 2 weeks to work on this.

**Comment by FooBarWidget** [comment]
The APT/YUM repositories are now served from a self-hosted mirror. We're no longer serving packages from Bintray. This eliminates problems due to Bintray brownouts. Our packages will stay available even when Bintray shuts down on March 1.

However, we still _publish_ to Bintray. The next step in the migration is to build a self-hosted package publishing system. Until this is done, the Fullstaq Ruby project will be unable to release any updates.

**Comment by FooBarWidget** [comment]
Today we launched a new APT and YUM repository for Fullstaq Ruby, as well as a new CI/CD process for testing and publishing packages.

I would appreciate a review of the following document, which describes how our new APT/YUM repo setup and publication process works: https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/blob/main/dev-handbook/apt-yum-repo.md

While conceptually simple, publishing APT/YUM repositories is actually riddled with many caveats. It's extremely non-trivial to set up a repository and a publishing process that's *reliable, highly available, consistent and plays well with CI/CD*. Special attention was given to the following problems:
- Atomic publishing
- Strong consistency
- Concurrency safe publishing
- Segregated, temporary repositories for testing
- Production data parity during testing
- Preservation of old package versions
- Optional overwrite protection
- Backups
